let PropertyObject = {
  address: '',
  active: false,
  admin_fee_amt: 0,
  admin_fee_refund: false,
  airconditioning: false,
  appalcart: false,
  bathroom_no: 1,
  bedroom_no: 1,
  campus_distance: 0,
  clean_fee_amt: 0,
  clean_fee_refund: false,
  clubhouse: false,
  contact_id: 0,
  contract_length: 0,
  created: 0,
  description: '',
  dishwasher: false,
  efficiency: false,
  furnished: false,
  heat_type: '',
  internet_type: 0,
  lease_type: 0,
  laundry_type: 0,
  monthly_rent: '',
  move_in_date: 0,
  name: '',
  other_fees: '',
  parking_fee: 0,
  parking_per_unit: 0,
  pet_deposit: 0,
  pet_dep_refund: false,
  pets_allowed: false,
  pet_fee: 0,
  pet_type: '',
  security_amt: 0,
  security_refund: false,
  student_type: 0,
  sublease: false,
  timeout: 0,
  trash_type: 0,
  updated: 0,
  util_water: false,
  util_trash: false,
  util_power: false,
  utilities_inc: false,
  tv_type: 0,
  window_number: false,
  workout_room: false,
  id : 0
}

export default PropertyObject
