const SubleaseObject = {
  additional_fees: '',
  address: '',
  airconditioning: '0',
  appalcart: '0',
  bathroom_no: '1',
  bedroom_no: '1',
  campus_distance: '0',
  contact_info: '0',
  description: '',
  dishwasher: '0',
  furnished: '0',
  internet_type: '1',
  landlord_perm: '0',
  laundry_type: '0',
  lease_type: '0',
  monthly_rent: '0',
  move_in_date: 0,
  move_out_date: 0,
  name: '',
  parking_per_unit: '1',
  pets_allowed: '0',
  proptype: '0',
  smoking_allowed: '0',
  trash_type: '0',
  tv_type: '0',
  utilities_inc: '0',
}

export default SubleaseObject
