sudo: false
language: php
php:
- 7
- hhvm

install:
- nvm install 6
- npm install

script:
- ".travis-build/phplint ."
- phpunit

after_success:
- npm run prod
- rm -rf node_modules
- tar -czf properties.tar.gz *

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TtX0sXkg24KUrb3Luy4QsiNQ4PofMl4cnnsSmchHhpNNFef5Lf3GmBfFEdk4qhMDleAzpfit42OUUwVJ0xY7o60SnKqFmkBlw1EKX0p2m8FxG/QK6QnxONgXsBh6huabvXaioZJstV5cVeKtGdPVxYbH6auVwbPXFd2bcMuX9rR2PjOMu6gtHHW34rUpkk0kkdgvmlP6htGEZRVlZbmnM1qfSBziCVNsRflAeFx2YjQb+M81m9t310RSmEOSnOl86SYhwF34+oYTn/WVtWgD2cSGqBhq/RQ9VTYlCl6raMvAv2gNxUbB3bJaHzEQjrOFt21WBOOfH4t3ZOlNCZ0O82krCBIkzSc+2XRy/pKkkG7XdbCG4Ncp7WUU+KbmbJQBtvlOzEiBfz1p6YaJFGUr3/TpI3jygubFYxrE58CiEzH1NPUNlakvZ94oXnqdcpfiQ8JTyH5aU4EJzzg57GVMn4NvZcuscQlM5QsM8+TS7w0ePh05WRslaRr5JA2khRgTSpt5mILQIvu9cid4cM36n3HDC3jTbxGFlesoso26W3q1bsa6Nt/oOSsqtHr0GJfjtnOxWK7QjHg+mpjSTWfwF7Cnh3zcRFVSNu7rrq4jkUfhl1Na4/OzvacV/rt+RjCt8v3/Vapu8Wt2JH4absGMpDUc1XpvpCatiLqvKiPgKcQ=
  file: properties.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/properties
    branch: master
    tags: true
