sudo: false
language: php
php:
- 7
install:
- nvm install 6
- npm install
script:
- ".travis-build/phplint ."
after_success:
- npm run build
- rm -rf node_modules
- tar -czf properties.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: vAkvWZGYnoiscwkdIXdlFd1Jce2smFEzYjGALhiK36aBjIkEIIebEZCoxEcqpgRmzhNe1J40aFDdQvMoDW6FVjo6XzLl9qFQW4FArt7xdxQblk0r7rOP3l1C39GvDay4+YLJzC0nhdCve+PAgJkKEtrJoQ+mTumjJGjJG73mVIOgHcCrjZQCIrRWo+W3xJ2+OScV69wjRiB9Mu1OBKGRQGC8zW5bRzIpjZxtTlZlY8cL3r2ko5aPxMN34WRK42i/uGUIAKztPlK2TsTLf8AF1uBLN9ErEP+eV5fzZkxSwBNjWLJbm+/0AwVfNJgMy+jaSglDeWn2c/jr1y1jD0qSRaIKO7GgIIp2WS3unCU5cEu1tFC+iZgTaERb4o1YU7uSc0ePzRGKjaSRacfDJm3776uBbwPHNXYNPiq3AruBgY5NmfS5DnEIVJVVWkSGiwx31n4VbKR6zNfAk4qHRHQiVuJULS+Lm64zMcnioJTKDmsxIoDxhcbdvroXj57aMhSfIFpqn7J4O2ALPgFIi8KFb352SVjNHA7bHt7vtqEyWm+JxXPSYRyef+wPk0Cml0HBgvUXLxnZMCPeFXdTE2euSXzYEK9uvxIsUOOPrhnLe8LUxuXAeT7qSzjegul2AP/lgyhfbiFZIFdGKew+SrVXqd++6bhWNKzV1M5HDC0srEs=
  file: properties.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/properties
    branch: master
    tags: true
